[package]
name = "blueshift_pinocchio_escrow"
version = "0.1.0"
edition = "2021"

[dependencies]
pinocchio = "0.9.2"
pinocchio-system = "0.3.0"
pinocchio-token = "0.4.0"
pinocchio-associated-token-account = "0.2"

[lib]
crate-type = ["lib", "cdylib"]
